spring:
  application:
    name: sso-provider

server:
  port: 8001

logging:
  level:
    root: warn

spring:
  datasource:
    name: sso
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode:true&characterEncoding:utf8&useSSL:false
    username: scolia
    password: db4me2job

spring:
  datasource:
    druid:
      initial-size: 2
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 2
    timeout: 0

# mybatis
mybatis:
  mapper-locations: classpath:win/scolia/sso/dao/*.xml

# pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true

# sso
sso:
  register:
    enable: false
  encrypt:
    salt: 00202df8-3e9b-463a-8c23-8ad5463cbb14
  cache:
    prefix: SSO
    expire: 2592000
    flush-expire: true
  cookie:
    max-age: 1209600
  page:
    size: 10

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://scolia:manager2euk@eureka.scolia.win/eureka
